package modules

import "github.com/akha-security/akca/engine/internal/models"

var GroupDRegistry = []ModuleDescriptor{
	{Manifest: models.PluginManifest{Name: "security_headers", Description: "Missing or weak security headers", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "cookie_security", Description: "Session and cookie security misconfigurations (Secure, HttpOnly, SameSite, __Host-)", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "tls_misconfig", Description: "TLS protocol and cipher misconfiguration", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "vulnerable_components", Description: "Technology and component version inventory", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "sensitive_data", Description: "Sensitive data exposure in responses", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "secret_exposure", Description: "Secret and credential exposure", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "cicd_exposure", Description: "Exposed CI/CD and build artifacts", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "git_recovery", Description: "Partial .git repository recovery and object enumeration", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "source_code_disclosure", Description: "Backup/source file disclosure and semantic code analysis", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "graphql", Description: "GraphQL introspection and schema analysis", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "script_source", Description: "Third-party script source and broken CDN link analysis", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "websocket", Description: "WebSocket SQLi/XSS/IDOR deep testing", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "cloud_storage", Description: "Cloud storage bucket exposure", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "cloud_posture", Description: "Cloud auth provider abuse and terraform state exposure", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "client_ssti", Description: "Client-side template injection", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "smuggling", Description: "HTTP request smuggling signals", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "prototype_pollution", Description: "Prototype pollution detection", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "insecure_deserialization", Description: "Insecure deserialization and object injection detection", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "ldap_xpath_injection", Description: "LDAP/XPath/header injection signals", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "crlf", Description: "CRLF response splitting / header injection", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "debug_admin", Description: "Debug and admin interface exposure", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "business_logic", Description: "Business logic testing signals", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "race_condition", Description: "Race condition detection", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "api_versioning", Description: "API versioning discovery", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "known_cve", Description: "Known CVE detection from embedded snapshot", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "actuator", Description: "Spring Boot Actuator exposure", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "backup_archives", Description: "Public backup archive exposure", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "cloud_takeover", Description: "Dangling cloud service DNS takeover", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "devops_exposure", Description: "DevOps and infrastructure endpoint exposure", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "host_poisoning", Description: "Host forwarding header poisoning", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "http_methods", Description: "Unsafe HTTP method exposure", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "ldap", Description: "LDAP injection error disclosure", Version: "0.1.0"}, Precondition: hasParameter},
	{Manifest: models.PluginManifest{Name: "xpath", Description: "XPath injection error disclosure", Version: "0.1.0"}, Precondition: hasParameter},
	{Manifest: models.PluginManifest{Name: "llm_injection", Description: "AI/LLM prompt injection and system prompt extraction", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "route_auth_bypass", Description: "Route authentication bypass via proxy/URL normalization discrepancies", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "tenant_isolation", Description: "Cross-tenant data isolation and multi-tenant authorization testing", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "account_recovery", Description: "Password reset and account recovery state machine testing", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "webhook_security", Description: "Webhook signature and replay verification testing", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "session_lifecycle", Description: "Session fixation and post-logout token lifecycle testing", Version: "0.1.0"}, Precondition: alwaysReady},
	{Manifest: models.PluginManifest{Name: "parser_differential", Description: "Parser differential and duplicate key precedence testing", Version: "0.1.0"}, Precondition: alwaysReady},
}
