package apinative

import (
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
)

type Format string

const (
	FormatOpenAPI            Format = "openapi"
	FormatPostman            Format = "postman"
	FormatPostmanEnvironment Format = "postman_environment"
	FormatHAR                Format = "har"
	FormatWSDL               Format = "wsdl"
	FormatGraphQL            Format = "graphql"
	FormatProto              Format = "grpc_proto"
	FormatAsyncAPI           Format = "asyncapi"
)

type Parameter struct {
	Name     string        `json:"name"`
	In       string        `json:"in"`
	Type     string        `json:"type,omitempty"`
	Format   string        `json:"format,omitempty"`
	Required bool          `json:"required"`
	Enum     []interface{} `json:"enum,omitempty"`
	Minimum  *float64      `json:"minimum,omitempty"`
	Maximum  *float64      `json:"maximum,omitempty"`
	Example  interface{}   `json:"example,omitempty"`
	Schema   interface{}   `json:"schema,omitempty"`
}

type Operation struct {
	ID              string                 `json:"id"`
	Method          string                 `json:"method"`
	Path            string                 `json:"path"`
	URL             string                 `json:"url,omitempty"`
	ContentType     string                 `json:"content_type,omitempty"`
	BodyTemplate    string                 `json:"body_template,omitempty"`
	Parameters      []Parameter            `json:"parameters,omitempty"`
	AuthSchemes     []string               `json:"auth_schemes,omitempty"`
	RequestSchema   interface{}            `json:"request_schema,omitempty"`
	ResponseSchemas map[string]interface{} `json:"response_schemas,omitempty"`
	SourceFormat    Format                 `json:"source_format"`
}

type Inventory struct {
	Title      string            `json:"title,omitempty"`
	Format     Format            `json:"format"`
	BaseURLs   []string          `json:"base_urls,omitempty"`
	Operations []Operation       `json:"operations"`
	Variables  map[string]string `json:"variables,omitempty"`
}

type ImportOptions struct {
	BaseURL     string
	Environment map[string]string
}

func (op Operation) ResolveURL(baseURL string) string {
	if op.URL != "" {
		return expandVariables(op.URL, nil)
	}
	base, err := url.Parse(baseURL)
	if err != nil || base.Host == "" {
		return op.Path
	}
	ref, err := url.Parse(op.Path)
	if err != nil {
		return op.Path
	}
	if strings.HasPrefix(op.Path, "/") {
		base.Path = ""
		base.RawQuery = ""
	}
	return base.ResolveReference(ref).String()
}

func RequestBodyFromSchema(schema interface{}) string {
	value := exampleForSchema(schema, 0)
	if value == nil {
		return ""
	}
	raw, _ := json.Marshal(value)
	return string(raw)
}

// RequestBodyParameters flattens a request schema into injectable dotted JSON
// paths while retaining each leaf's type constraints. Arrays use index zero,
// matching the representative body generated by RequestBodyFromSchema.
func RequestBodyParameters(schema interface{}) []Parameter {
	var out []Parameter
	collectBodyParameters("", schema, &out, 0)
	return out
}

func collectBodyParameters(prefix string, raw interface{}, out *[]Parameter, depth int) {
	if depth > 12 {
		return
	}
	schema, ok := raw.(map[string]interface{})
	if !ok {
		return
	}
	kind := strings.ToLower(stringValue(schema["type"]))
	if kind == "" && schema["properties"] != nil {
		kind = "object"
	}
	switch kind {
	case "object":
		properties, _ := schema["properties"].(map[string]interface{})
		requiredSet := map[string]struct{}{}
		if required, ok := schema["required"].([]interface{}); ok {
			for _, item := range required {
				requiredSet[stringValue(item)] = struct{}{}
			}
		}
		for _, key := range sortedKeys(properties) {
			childPath := key
			if prefix != "" {
				childPath = prefix + "." + key
			}
			before := len(*out)
			collectBodyParameters(childPath, properties[key], out, depth+1)
			if _, required := requiredSet[key]; required {
				for index := before; index < len(*out); index++ {
					(*out)[index].Required = true
				}
			}
		}
	case "array":
		childPath := "0"
		if prefix != "" {
			childPath = prefix + ".0"
		}
		collectBodyParameters(childPath, schema["items"], out, depth+1)
	default:
		if prefix == "" {
			return
		}
		parameter := Parameter{
			Name: prefix, In: "json", Type: kind, Format: stringValue(schema["format"]),
			Example: schema["example"], Schema: schema,
		}
		parameter.Enum, _ = schema["enum"].([]interface{})
		if minimum, ok := numberValue(schema["minimum"]); ok {
			parameter.Minimum = &minimum
		}
		if maximum, ok := numberValue(schema["maximum"]); ok {
			parameter.Maximum = &maximum
		}
		*out = append(*out, parameter)
	}
}

func exampleForSchema(raw interface{}, depth int) interface{} {
	if depth > 8 {
		return nil
	}
	schema, ok := raw.(map[string]interface{})
	if !ok {
		return nil
	}
	if value, exists := schema["example"]; exists {
		return value
	}
	if value, exists := schema["default"]; exists {
		return value
	}
	if values, ok := schema["enum"].([]interface{}); ok && len(values) > 0 {
		return values[0]
	}
	switch strings.ToLower(stringValue(schema["type"])) {
	case "object", "":
		properties, _ := schema["properties"].(map[string]interface{})
		if len(properties) == 0 {
			return nil
		}
		out := make(map[string]interface{}, len(properties))
		for key, child := range properties {
			out[key] = exampleForSchema(child, depth+1)
		}
		return out
	case "array":
		return []interface{}{exampleForSchema(schema["items"], depth+1)}
	case "integer", "number":
		if minimum, ok := numberValue(schema["minimum"]); ok {
			return minimum
		}
		return 1
	case "boolean":
		return true
	case "string":
		switch stringValue(schema["format"]) {
		case "uuid":
			return "00000000-0000-4000-8000-000000000001"
		case "date-time":
			return "2026-01-01T00:00:00Z"
		case "email":
			return "akca@example.test"
		case "uri", "url":
			return "https://example.test/"
		case "hostname":
			return "example.test"
		case "ipv4":
			return "192.0.2.1"
		default:
			return "akca"
		}
	default:
		return nil
	}
}

func expandVariables(value string, variables map[string]string) string {
	for key, replacement := range variables {
		value = strings.ReplaceAll(value, "{{"+key+"}}", replacement)
	}
	return value
}

func joinURL(baseURL, endpointPath string) string {
	base, err := url.Parse(baseURL)
	if err != nil || base.Host == "" {
		return endpointPath
	}
	base.Path = path.Join(base.Path, endpointPath)
	if strings.HasSuffix(endpointPath, "/") && !strings.HasSuffix(base.Path, "/") {
		base.Path += "/"
	}
	return base.String()
}

func stringValue(value interface{}) string {
	if value == nil {
		return ""
	}
	if text, ok := value.(string); ok {
		return text
	}
	return fmt.Sprint(value)
}

func numberValue(value interface{}) (float64, bool) {
	switch typed := value.(type) {
	case float64:
		return typed, true
	case int:
		return float64(typed), true
	default:
		return 0, false
	}
}
